name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./backend   # Set to the correct folder
        run: npm install

      # Start NestJS server in the background
      - name: Start NestJS server
        working-directory: ./backend
        run: npm run start &
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db

      - name: Set up Prisma
        working-directory: ./backend   # Set to the correct folder
        run: npx prisma migrate deploy --schema=prisma/schema.prisma
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db  # Add the DATABASE_URL here

      - name: Run Unit Tests
        working-directory: ./backend   # Set to the correct folder
        run: npm test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db

      # Wait for the server to be up and running before starting Cypress
      - name: Wait for server to be ready
        run: |
          npx wait-on http://localhost:3000

      - name: Run Cypress E2E Tests
        working-directory: ./backend   # Set to the correct folder
        run: npx cypress run
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
